[package]
name = "graphics-3d"
version = "0.1.0"
edition = "2024"

[lib]
name = "g3d"
path = "src/lib.rs"

[[bin]]
name = "g3d-app"
path = "src/main.rs"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
rfd = "0.15.4"
image = "0.25.8"